Fix using the Mocha API
iensu/mocha-cakes-2 pull request #21
Opened 2018-03-26 15:01 UTC by EvilOatmeal

When Mocha is run using the CLI [the default reporter is first set up](https://github.com/mochajs/mocha/blob/v5.0.5/bin/_mocha#L21), which sets `context.xit`, and [then that setup is overriden](https://github.com/mochajs/mocha/blob/v5.0.5/bin/_mocha#L472) by the reporter you've specified in the options, so the non-default reporter can "inherit" parts of the default reporter by not overriding them.

But when you use the API and construct Mocha with the _ui_ option (`const mocha = new Mocha({ui: 'mocha-cakes-2'})`) the default reporter isn't set up first so Mocha will throw an error when it runs `exports.xit = context.xit || context.test.skip` because mocha-cakes-2 has not set `context.xit` or `context.test`.

2018-03-26 19:41 UTC, iensu requested changes
Thank you for your PR, this looks really great! One small thing, would be great if you could add a line or two about the MOCHA_INTERFACE env variable in the README. Also see the comment above regarding making it optional.

2018-03-26 19:41 UTC, iensu commented on test/helpers.js
> +    throw new Error("The MOCHA_INTERFACE environment variable must be set to one of:", Object.keys(interfaces).join(', '));
Making the MOCHA_INTERFACE env variable obligatory will probably break the setup for some people, so I would prefer you to use the `cli` interface if none is specified.

2018-03-27 10:48 UTC, EvilOatmeal commented
Good points! I've made `cli` the default interface and updated the README.

2018-03-27 15:13 UTC, iensu approved these changes

2018-03-27 15:13 UTC, iensu commented
Looking good! Thanks a lot!

2018-03-27 15:13 UTC, merged

2018-03-27 15:52 UTC, iensu commented
PR has been merged and published to NPM under version 3.3.0! Thanks again for your PR!